
jwt:
  header: Authorization
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N
  expiration: 120000   #毫秒
  route:
    login: /auth/login
    refresh: /auth/refresh
    register: /auth/register

security:
  ignored:
    urls:
      - /swagger-ui.html
      - swagger-resources/**
      - /api/auth/login
      - /api/auth/refreshToken
      - /api/role/getAll
#mybatis配置

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
